#version: '3.9'

services:
  # ---------------------------
  # Spring Boot Application
  # ---------------------------
  app:
    build: .
    container_name: order-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: danial
      SPRING_DATASOURCE_PASSWORD: nopass
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # Optional: profiles or other settings
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - shared-net

# ---------------------------
# Docker Volumes & Network
# ---------------------------
volumes:
  mysql_data:

networks:
  shared-net:
    external: true
