server:
  port: 8086
spring:
  application:
    name: order-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/order_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: danial
    password: nopass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # enable idempotence for producer safety (optional)
      properties:
        enable.idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.oms.events,com.oms.dto,java.util"
      group-id: order-service
    listener:
      concurrency: 3

topics:
  order-created: orders.created
  inventory-reserved: inventory.reserved
  inventory-reservation-failed: inventory.reservation.failed
  inventory-release: inventory.release
  payment-success: payment.success
  payment-failed: payment.failed
  order-validation-request: order.validation.request
  order-cancelled: orders.cancelled
  order-status-updated: orders.status.updated

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true



