server:
  port: 8084
spring:
  application:
    name: product-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/product_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: danial
    password: nopass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: host.docker.internal:9092
    admin:
      auto-create: true   # enables KafkaAdmin
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # enable idempotence for producer safety (optional)
      properties:
        enable.idempotence: true
    consumer:
      group-id: customer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.oms.product.events,com.oms.product.dto,java.util"
    listener:
      concurrency: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

topics:
  order-validation-request: order.validation.request
  product-validation-result: product.validation.result
