server:
  port: 8082
spring:
  application:
    name: inventory-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: danial
    password: nopass
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always            # ✅ Force schema.sql to run
#      continue-on-error: true # ✅ Optional, won't fail on minor SQL errors
#      schema-locations: classpath:schema-mysql.sql # ✅ Explicit location
#      data-locations: classpath:data.sql
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

